<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Nuget">
	<IsPackable>true</IsPackable>

	<Title>Immediate.Jobs.Redis</Title>
	<Description>Redis queue and recurring storage provider for Immediate.Jobs.</Description>
	<PackageTags>background-jobs;scheduler;redis;distributed</PackageTags>
  </PropertyGroup>

  <ItemGroup Label="Nuget">
	<None Include="readme.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
	<Features>runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
	<Using Include="Immediate.Jobs.Shared" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="../Immediate.Jobs.Shared/Immediate.Jobs.Shared.csproj" PrivateAssets="all" />
	<ProjectReference Include="../Immediate.Jobs/Immediate.Jobs.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Immediate.Jobs.StorageTests" />
  </ItemGroup>

</Project>
