// <auto-generated />
using System;
using Immediate.Jobs.DistributedAspire.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Immediate.Jobs.DistributedAspire.Shared.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    partial class JobsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Immediate.Jobs.DistributedAspire.Shared.Data.BatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("Guid");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bytea")
                        .HasColumnName("HashCode");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("BatchableRows");
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateFairQueueGroupEntity", b =>
                {
                    b.Property<string>("QueueName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<long>("LastServedSequence")
                        .HasColumnType("bigint");

                    b.HasKey("QueueName", "GroupId");

                    b.ToTable("immediate_fair_queue_groups", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobBatchEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("bigint");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("State", "CompletedAt");

                    b.ToTable("immediate_job_batches", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobContinuationEntity", b =>
                {
                    b.Property<string>("ChildJobHandle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<short>("ParentKind")
                        .HasColumnType("smallint");

                    b.Property<string>("ParentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Delay")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<short>("ParentOutcome")
                        .HasColumnType("smallint");

                    b.Property<short>("Trigger")
                        .HasColumnType("smallint");

                    b.HasKey("ChildJobHandle", "ParentKind", "ParentId");

                    b.HasIndex("ParentKind", "ParentId");

                    b.ToTable("immediate_job_continuations", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("BatchHandle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("DueAt")
                        .HasColumnType("bigint");

                    b.Property<string>("ExecutionSpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long?>("ExecutionStartedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("ExecutionTraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("FailedDependencies")
                        .HasColumnType("integer");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("default");

                    b.Property<string>("RecurringKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RemainingDependencies")
                        .HasColumnType("integer");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TraceState")
                        .HasColumnType("text");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BatchHandle");

                    b.HasIndex("RecurringKey")
                        .IsUnique();

                    b.HasIndex("State", "CreatedAt");

                    b.HasIndex("State", "DueAt");

                    b.HasIndex("QueueName", "State", "GroupId");

                    b.HasIndex("QueueName", "State", "DueAt", "CreatedAt");

                    b.ToTable("immediate_jobs", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobExecutionEntity", b =>
                {
                    b.Property<string>("JobHandle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<long?>("AcquiredAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionSpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long?>("ExecutionStartedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("ExecutionTraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsSynthetic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("JobHandle", "Attempt");

                    b.ToTable("immediate_job_executions", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobServerEntity", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ActiveWorkers")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<long>("LastHeartbeat")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxWorkers")
                        .HasColumnType("integer");

                    b.HasKey("WorkerId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("immediate_job_servers", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateRecurringJobEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsCodeDefined")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("LastRunAt")
                        .HasColumnType("bigint");

                    b.Property<long>("NextRunAt")
                        .HasColumnType("bigint");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Name");

                    b.HasIndex("IsPaused", "NextRunAt");

                    b.ToTable("immediate_recurring_jobs", (string)null);
                });

            modelBuilder.Entity("Immediate.Jobs.DistributedAspire.Shared.Data.BatchEntity", b =>
                {
                    b.OwnsOne("Immediate.Jobs.DistributedAspire.Shared.Data.PostgresDateTimeOffset", "ModifiedOn", b1 =>
                        {
                            b1.Property<int>("BatchEntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("LocalDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LocalDateTime");

                            b1.Property<string>("TimeZoneName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TimeZoneName");

                            b1.Property<TimeSpan>("TimeZoneOffset")
                                .HasColumnType("interval")
                                .HasColumnName("TimeZoneOffset");

                            b1.Property<DateTimeOffset>("UtcDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("UtcDateTime");

                            b1.HasKey("BatchEntityId");

                            b1.ToTable("BatchableRows");

                            b1.WithOwner()
                                .HasForeignKey("BatchEntityId");
                        });

                    b.Navigation("ModifiedOn");
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobContinuationEntity", b =>
                {
                    b.HasOne("Immediate.Jobs.EntityFrameworkCore.ImmediateJobEntity", null)
                        .WithMany()
                        .HasForeignKey("ChildJobHandle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobEntity", b =>
                {
                    b.HasOne("Immediate.Jobs.EntityFrameworkCore.ImmediateJobBatchEntity", null)
                        .WithMany()
                        .HasForeignKey("BatchHandle")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Immediate.Jobs.EntityFrameworkCore.ImmediateJobExecutionEntity", b =>
                {
                    b.HasOne("Immediate.Jobs.EntityFrameworkCore.ImmediateJobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobHandle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
