<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Nuget">
	<IsPackable>true</IsPackable>

    <Title>Immediate.Jobs.LinqToDB</Title>
    <Description>LinqToDB storage provider for Immediate.Jobs.</Description>
    <PackageTags>background-jobs;scheduler;linq2db;postgresql;sqlite;sql-server</PackageTags>
  </PropertyGroup>

  <ItemGroup Label="Nuget">
	<None Include="readme.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
	<Features>runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
	<Using Include="Immediate.Jobs.Shared" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="linq2db" />
	<PackageReference Include="linq2db.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Immediate.Jobs.Shared/Immediate.Jobs.Shared.csproj" PrivateAssets="all" />
	<ProjectReference Include="../Immediate.Jobs/Immediate.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Immediate.Jobs.StorageTests" />
  </ItemGroup>

</Project>
