<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS1591;CA1050;CA1848;CA1873</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net8.0' ">roslyn4.8</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net10.0' ">roslyn5.0</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net11.0' ">roslyn5.9</RoslynVersion>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../../src/Immediate.Jobs/Immediate.Jobs.csproj" />
	<ProjectReference Include="../../../src/Immediate.Jobs.NodaTime/Immediate.Jobs.NodaTime.csproj" />
	<ProjectReference Include="../../../src/Immediate.Jobs.EntityFrameworkCore/Immediate.Jobs.EntityFrameworkCore.csproj" />
	
	<ProjectReference Include="../../../src/Immediate.Jobs.Analyzers/Immediate.Jobs.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>

	<ProjectReference Include="../../../src/Immediate.Jobs.Generators/Immediate.Jobs.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>

	<ProjectReference Include="..\..\..\src\Immediate.Jobs.Shared\Immediate.Jobs.Shared.csproj" />
  </ItemGroup>

</Project>
