<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<_SkipUpgradeNetAnalyzersNuGetWarning>true</_SkipUpgradeNetAnalyzersNuGetWarning>
	<!-- Temporary fix for packaging bug -->
	<NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
	<Features>runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Immediate.Handlers" GeneratePathProperty="true" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
	<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	<PackageReference Include="NodaTime" />
	<PackageReference Include="Scriban" />
	<PackageReference Include="Verify.SourceGenerators" />
	<PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
	<PackageReference Include="Basic.Reference.Assemblies.Net110" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
	<PackageReference Include="Basic.Reference.Assemblies.Net100" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
	<PackageReference Include="Basic.Reference.Assemblies.Net90" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
	<PackageReference Include="Basic.Reference.Assemblies.Net80" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Jobs.Shared/Immediate.Jobs.Shared.csproj" />
	<ProjectReference Include="../../src/Immediate.Jobs.NodaTime/Immediate.Jobs.NodaTime.csproj" />
  </ItemGroup>

  <PropertyGroup>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net8.0' ">roslyn4.8</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net10.0' ">roslyn5.0</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net11.0' ">roslyn5.9</RoslynVersion>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Jobs.Analyzers/Immediate.Jobs.Analyzers.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
	<Reference Include="../../src/Immediate.Jobs.Analyzers/bin/$(Configuration)/$(RoslynVersion)/Immediate.Jobs.Analyzers.dll" />

	<ProjectReference Include="../../src/Immediate.Jobs.Generators/Immediate.Jobs.Generators.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
	<Reference Include="../../src/Immediate.Jobs.Generators/bin/$(Configuration)/$(RoslynVersion)/Immediate.Jobs.Generators.dll" />

	<Reference Include="$(PkgImmediate_Handlers)/analyzers/dotnet/$(RoslynVersion)/cs/Immediate.Handlers.Generators.dll" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" GeneratePathProperty="true" PrivateAssets="all" />
	<Reference Include="$(PkgMicrosoft_CodeAnalysis_NetAnalyzers)/analyzers/dotnet/cs/Microsoft.CodeAnalysis.NetAnalyzers.dll" />
  </ItemGroup>

</Project>
