<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
	<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	<IsRoslynComponent>true</IsRoslynComponent>
  </PropertyGroup>

  <ItemGroup>
	<Compile Include="../Common/*.cs" Link="Common/%(Filename).cs" />
  </ItemGroup>

  <ItemGroup>
	<None Remove="Templates/*.sbntxt" />
	<EmbeddedResource Include="Templates/*.sbntxt" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AssemblyMetadata.Generators" PrivateAssets="all" />
	<PackageReference Include="Meziantou.Framework.Scheduling" GeneratePathProperty="true" PrivateAssets="all" />
	<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>

  <!-- netstandard2.0 dependencies -->
  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
	<PackageReference Include="Scriban" PrivateAssets="all" IncludeAssets="Build" />
  </ItemGroup>

  <PropertyGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
	<PackageScribanIncludeSource>true</PackageScribanIncludeSource>
	<DefineConstants>$(DefineConstants);SCRIBAN_NO_ASYNC</DefineConstants>
  </PropertyGroup>

  <Target Name="GetDependencyTargetPaths" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
	<ItemGroup>
	  <TargetPathWithTargetPlatformMoniker Include="$(PkgMeziantou_Framework_Scheduling)/lib/netstandard2.0/Meziantou.Framework.Scheduling.dll" IncludeRuntimeDependency="false" />
	</ItemGroup>
  </Target>

  <!-- net10.0 dependencies -->
  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
	<PackageReference Include="Scriban" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
	<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="GetDependencyTargetPaths" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
	<ItemGroup>
	  <TargetPathWithTargetPlatformMoniker Include="$(PkgScriban)/lib/net8.0/Scriban.dll" IncludeRuntimeDependency="false" />
	  <TargetPathWithTargetPlatformMoniker Include="$(PkgMeziantou_Framework_Scheduling)/lib/net10.0/Meziantou.Framework.Scheduling.dll" IncludeRuntimeDependency="false" />
	</ItemGroup>
  </Target>

</Project>
