//HintName: IJ.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Immediate.Jobs.Testing;

public static class ImmediateJobsGeneratedServiceCollectionExtensions
{
	public static global::Immediate.Jobs.Shared.IImmediateJobsBuilder AddTestsJobs(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		params global::System.ReadOnlySpan<string> tags
	)
	{
		var builder = global::Immediate.Jobs.Shared.ImmediateJobsRuntimeServiceCollectionExtensions.AddImmediateJobsCore(services);
		
		if (tags is [] || Intersects(tags, ["critical"]))
		{
			global::WorkJob.AddJob(services);
		}

		return builder;
	}

	// old-fashioned inner-loop; should be fine since neither tags list will ever be large
	private static bool Intersects(
		global::System.ReadOnlySpan<string> first,
		global::System.ReadOnlySpan<string> second
	)
	{
		foreach (var f in first)
		{
			foreach (var s in second)
			{
				if (string.Equals(f, s, global::System.StringComparison.Ordinal))
					return true;
			}
		}

		return false;
	}
}
