//HintName: IJ..WorkJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class WorkJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.Storage.IJobStorage storage,
		global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.Interfaces.IIdGenerator idGenerator
		, global::WorkContextExtractor contextExtractor0
	) : global::Immediate.Jobs.Shared.JobScheduler<global::Immediate.Jobs.Shared.EmptyJobRequest>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"work",
		"critical-queue",
		static options => new PayloadJsonContext(options).Payload
	)
		, global::Immediate.Jobs.Shared.Interfaces.IRecurringJobScheduler
	{
		protected override string? CaptureContext()
		{
			var keys = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);
			var slices = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal);
			if (!keys.Add(contextExtractor0.Key))
				throw new global::Immediate.Jobs.Shared.ImmediateJobException($"Multiple job context extractors use the key '{contextExtractor0.Key}'.");

			var context0 = contextExtractor0.Capture();
			if (context0 is not null)
			{
				global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.AddSlice(
					slices,
					contextExtractor0.Key,
					Serializer.Serialize(context0, static options => new PayloadJsonContext(options).Context0)
				);
			}
			return global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.Create(slices);
		}


		public global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> TriggerNowAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
			EnqueueAsync(default, cancellationToken);

		public global::System.Threading.Tasks.ValueTask AddOrUpdateRecurringAsync(string name, string cron, string timeZone = "UTC", global::System.Threading.CancellationToken cancellationToken = default) =>
			AddOrUpdateRecurringCoreAsync(name, cron, timeZone, cancellationToken);

		public global::System.Threading.Tasks.ValueTask RemoveRecurringAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) =>
			RemoveRecurringCoreAsync(name, cancellationToken);
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker(global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer) : global::Immediate.Jobs.Shared.Interfaces.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{
			if (execution.Record.Context is { } envelope)
			{
				var contextSlices = global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.Read(envelope);

				var contextExtractor0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::WorkContextExtractor>(scopedServices);
				if (contextSlices.Remove(contextExtractor0.Key, out var serializedContext0))
				{
					var context0 = serializer.Deserialize(serializedContext0, static options => new PayloadJsonContext(options).Context0);
					contextExtractor0.Restore(context0);
				}

				global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.LogOrphanedSlices(scopedServices, execution.Record, contextSlices.Keys);
			}

			var payload = new global::Immediate.Jobs.Shared.EmptyJobRequest();

			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(execution)
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::WorkJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		/// <summary>Generic reified method to support `struct`s with explicitly implemented properties</summary>
		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	internal sealed record JobDefinition : global::Immediate.Jobs.Shared.Internals.JobDefinition;

	internal static WorkJob.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) =>
		new()
    	{
    		Name = "work",
			Queue = new global::Immediate.Jobs.Shared.Internals.JobQueueDefinition
    		{
    			Name = "critical-queue",
    			Priority = 10,
    			Concurrency = 1,
    		},
    		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
    		JobType = typeof(global::WorkJob),
    		TimeZone = "UTC",
    		MaxAttempts = 3,
    		MaxConcurrency = 0,
    		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
    		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
    		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
    	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::Immediate.Jobs.Shared.EmptyJobRequest))
				return CreateTypeInfo0(options);

			if (type == typeof(string))
				return CreateTypeInfo1(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest>)GetTypeInfo(
				typeof(global::Immediate.Jobs.Shared.EmptyJobRequest)
			)!;

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> Context0 =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)GetTypeInfo(
				typeof(string)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Immediate.Jobs.Shared.EmptyJobRequest>
			{
				ObjectCreator = static () => new global::Immediate.Jobs.Shared.EmptyJobRequest(),
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Immediate.Jobs.Shared.EmptyJobRequest>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<
				global::Immediate.Jobs.Shared.Internals.JobDefinition,
				WorkJob.JobDefinition
			>(WorkJob.CreateJobDefinition)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<WorkJob.Scheduler>(services);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<WorkJob.Invoker>(services);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::WorkContextExtractor>(services);

		return services;
	}
}
