//HintName: IH..WorkJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

partial class WorkJob
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::Immediate.Jobs.Shared.EmptyJobRequest, global::System.ValueTuple>
	{
		private readonly global::WorkJob.HandleBehavior _handleBehavior;

		public Handler(
			global::WorkJob.HandleBehavior handleBehavior
		)
		{
			var handlerType = typeof(WorkJob);

			_handleBehavior = handleBehavior;

		}

		public async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::Immediate.Jobs.Shared.EmptyJobRequest request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _handleBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::Immediate.Jobs.Shared.EmptyJobRequest, global::System.ValueTuple>
	{
		private readonly global::WorkJob _container;

		public HandleBehavior(
			global::WorkJob container
		)
		{
			_container = container;
		}

		public override async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::Immediate.Jobs.Shared.EmptyJobRequest request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			await _container
				.HandleAsync(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);

			return default;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::WorkJob.Handler),
				typeof(global::WorkJob.Handler),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::Immediate.Handlers.Shared.IHandler<global::Immediate.Jobs.Shared.EmptyJobRequest, global::System.ValueTuple>),
				typeof(global::WorkJob.Handler),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::WorkJob.HandleBehavior),
				typeof(global::WorkJob.HandleBehavior),
				lifetime
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::WorkJob),
				typeof(global::WorkJob),
				lifetime
			)
		);

		return services;
	}
}
