//HintName: IJ.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static class ImmediateJobsGeneratedServiceCollectionExtensions
{
	public static global::Immediate.Jobs.Shared.ImmediateJobsBuilder AddTestsJobs(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::System.Action<global::Immediate.Jobs.Shared.ImmediateJobsOptions>? configure = null,
		params string[] tags
	)
	{
		var builder = global::Immediate.Jobs.Shared.ImmediateJobsRuntimeServiceCollectionExtensions.AddImmediateJobsCore(services, configure);

		return builder;
	}

	// old-fashioned inner-loop; should be fine since neither tags list will ever be large
	private static bool Intersects(
		global::System.ReadOnlySpan<string> first,
		global::System.ReadOnlySpan<string> second
	)
	{
		foreach (var f in first)
		{
			foreach (var s in second)
			{
				if (string.Equals(f, s, global::System.StringComparison.Ordinal))
					return true;
			}
		}

		return false;
	}
}
