//HintName: IJOB.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Microsoft.Extensions.DependencyInjection;

public static class ImmediateJobsGeneratedServiceCollectionExtensions
{
	public static global::Immediate.Jobs.Shared.ImmediateJobsBuilder AddImmediateJobs(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::System.Action<global::Immediate.Jobs.Shared.ImmediateJobsOptions>? configure = null,
		params string[] tags
	)
	{
		var builder = global::Microsoft.Extensions.DependencyInjection.ImmediateJobsRuntimeServiceCollectionExtensions.AddImmediateJobsCore(services, configure);
		services.AddSingleton(new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "critical-queue",
			Priority = 10,
			Concurrency = 1,
		});
		if (tags is [] || Intersects(tags, ["critical"]))
		{
		global::WorkJob.AddHandlers(services);
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::WorkJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::WorkJob.IScheduler), provider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::WorkJob.Scheduler>(provider));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(global::WorkJob.Invoker));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::WorkContextExtractor));
		services.AddSingleton<global::Immediate.Jobs.Shared.JobDefinition>(provider => global::WorkJob.CreateJobDefinition(provider));
		}
		return builder;
	}

	// old-fashioned inner-loop; should be fine since neither tags list will ever be large
	private static bool Intersects(
		global::System.ReadOnlySpan<string> first,
		global::System.ReadOnlySpan<string> second
	)
	{
		foreach (var f in first)
		{
			foreach (var s in second)
			{
				if (string.Equals(f, s, global::System.StringComparison.Ordinal))
					return true;
			}
		}

		return false;
	}
}
