//HintName: IH..CleanupSessionsJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

partial class CleanupSessionsJob
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::Immediate.Jobs.NoPayload, global::System.ValueTuple>
	{
		private readonly global::CleanupSessionsJob.HandleBehavior _handleBehavior;

		public Handler(
			global::CleanupSessionsJob.HandleBehavior handleBehavior
		)
		{
			var handlerType = typeof(CleanupSessionsJob);

			_handleBehavior = handleBehavior;

		}

		public async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::Immediate.Jobs.NoPayload request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _handleBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::Immediate.Jobs.NoPayload, global::System.ValueTuple>
	{
		private readonly global::CleanupSessionsJob _container;

		public HandleBehavior(
			global::CleanupSessionsJob container
		)
		{
			_container = container;
		}

		public override async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::Immediate.Jobs.NoPayload request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			await _container
				.HandleAsync(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);

			return default;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		services.Add(new(typeof(global::CleanupSessionsJob.Handler), typeof(global::CleanupSessionsJob.Handler), lifetime));
		services.Add(new(typeof(global::Immediate.Handlers.Shared.IHandler<global::Immediate.Jobs.NoPayload, global::System.ValueTuple>), typeof(global::CleanupSessionsJob.Handler), lifetime));
		services.Add(new(typeof(global::CleanupSessionsJob.HandleBehavior), typeof(global::CleanupSessionsJob.HandleBehavior), lifetime));
		services.Add(new(typeof(global::CleanupSessionsJob), typeof(global::CleanupSessionsJob), lifetime));
		return services;
	}
}
