//HintName: IJOB.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace Microsoft.Extensions.DependencyInjection;

public static class ImmediateJobsGeneratedServiceCollectionExtensions
{
	public static global::Immediate.Jobs.ImmediateJobsBuilder AddImmediateJobs(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::System.Action<global::Immediate.Jobs.ImmediateJobsOptions>? configure = null
	)
	{
		var builder = global::Microsoft.Extensions.DependencyInjection.ImmediateJobsRuntimeServiceCollectionExtensions.AddImmediateJobsCore(services, configure);
		global::WorkJob.AddHandlers(services);
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::WorkJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::WorkJob.IScheduler), provider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::WorkJob.Scheduler>(provider));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(global::WorkJob.Invoker));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::LoggingBehavior<global::WorkJob.Payload>));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::MetricsBehavior<global::WorkJob.Payload>));
		services.AddSingleton<global::Immediate.Jobs.JobDefinition>(provider => global::WorkJob.CreateJobDefinition(provider));
		return builder;
	}
}
