//HintName: IJOB.global..Example.SendEmailJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


namespace Example;


public partial class SendEmailJob
{

		public interface IScheduler : global::Immediate.Jobs.Shared.IJobScheduler<global::Example.SendEmailJob.Payload>;

		public sealed class Scheduler(
			global::Immediate.Jobs.Shared.IJobStorage storage,
			global::Immediate.Jobs.Shared.IJobSerializer serializer,
			global::System.TimeProvider timeProvider
		) : global::Immediate.Jobs.Shared.JobScheduler<global::Example.SendEmailJob.Payload>(storage, serializer, timeProvider, "send-email", "default", static options => new PayloadJsonContext(options).Payload), IScheduler
		{

		}


	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]

		internal sealed class Invoker(global::Immediate.Jobs.Shared.IJobSerializer serializer) : global::Immediate.Jobs.Shared.IJobInvoker

	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{


						var payload = serializer.Deserialize(execution.Record.Payload, static options => new PayloadJsonContext(options).Payload);


			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(
					execution.Record.Id,
					execution.Record.JobName,
					execution.Record.QueueName,
					execution.Record.Attempt,
					execution.Record.CreatedAt,
					execution.Record.DueAt
				)
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Example.SendEmailJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "send-email",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::Example.SendEmailJob),

		TimeZone = "UTC",
		MaxAttempts = 5,

				Timeout = global::System.TimeSpan.Parse("00:02:00", global::System.Globalization.CultureInfo.InvariantCulture),

		MaxConcurrency = 0,
		OverlapPolicy = (global::Immediate.Jobs.Shared.OverlapPolicy)0,
		Backoff = (global::Immediate.Jobs.Shared.BackoffStrategy)2,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{

						if (type == typeof(global::Example.SendEmailJob.Payload)) return CreateTypeInfo0(options);

						if (type == typeof(global::System.Guid)) return CreateTypeInfo1(options);

						if (type == typeof(string)) return CreateTypeInfo2(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Example.SendEmailJob.Payload> Payload => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Example.SendEmailJob.Payload>)GetTypeInfo(typeof(global::Example.SendEmailJob.Payload))!;



				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Example.SendEmailJob.Payload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
				{

						var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Example.SendEmailJob.Payload>
						{

								ObjectWithParameterizedConstructorCreator = static args => new global::Example.SendEmailJob.Payload((global::System.Guid)args[0], (string)args[1]),
								ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
								{

										new() { Name = "UserId", ParameterType = typeof(global::System.Guid), Position = 0, HasDefaultValue = false, DefaultValue = default(global::System.Guid) },

										new() { Name = "Template", ParameterType = typeof(string), Position = 1, HasDefaultValue = false, DefaultValue = default(string) },

								},

							PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
							{

										global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Guid>(options, new()
										{
											IsProperty = true,
											IsPublic = true,
											DeclaringType = typeof(global::Example.SendEmailJob.Payload),
											PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Guid>)options.GetTypeInfo(typeof(global::System.Guid)),
											Getter = static obj => ((global::Example.SendEmailJob.Payload)obj).UserId,

												Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),

											PropertyName = "UserId",
										}),

										global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, new()
										{
											IsProperty = true,
											IsPublic = true,
											DeclaringType = typeof(global::Example.SendEmailJob.Payload),
											PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
											Getter = static obj => ((global::Example.SendEmailJob.Payload)obj).Template,

												Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),

											PropertyName = "Template",
										}),

							},
						};
						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Example.SendEmailJob.Payload>(options, objectInfo);

					info.OriginatingResolver = this;
					return info;
				}


				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Guid> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
				{

						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::System.Guid>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GuidConverter);

					info.OriginatingResolver = this;
					return info;
				}


				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> CreateTypeInfo2(global::System.Text.Json.JsonSerializerOptions options)
				{

						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);

					info.OriginatingResolver = this;
					return info;
				}

	}
}
