//HintName: IJ..PlainRequestJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class PlainRequestJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.IJobStorage storage,
		global::Immediate.Jobs.Shared.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.IIdGenerator idGenerator
	) : global::Immediate.Jobs.Shared.JobScheduler<global::PlainRequestJob.Payload>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"plain-request",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
	{
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker(global::Immediate.Jobs.Shared.IJobSerializer serializer) : global::Immediate.Jobs.Shared.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{

			var payload = serializer.Deserialize(execution.Record.Payload, static options => new PayloadJsonContext(options).Payload);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::PlainRequestJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "plain-request",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::PlainRequestJob),
		TimeZone = "UTC",
		MaxAttempts = 3,
		MaxConcurrency = 0,
		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::PlainRequestJob.Payload))
				return CreateTypeInfo0(options);

			if (type == typeof(string))
				return CreateTypeInfo1(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::PlainRequestJob.Payload> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::PlainRequestJob.Payload>)GetTypeInfo(
				typeof(global::PlainRequestJob.Payload)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::PlainRequestJob.Payload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::PlainRequestJob.Payload>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::PlainRequestJob.Payload((string)args[0]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "Value", ParameterType = typeof(string), Position = 0, HasDefaultValue = false, DefaultValue = default(string) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::PlainRequestJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
						Getter = static obj => ((global::PlainRequestJob.Payload)obj).Value,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Value",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::PlainRequestJob.Payload>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		services.Add(
			new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
				typeof(global::Immediate.Jobs.Shared.JobDefinition),
				PlainRequestJob.CreateJobDefinition,
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(PlainRequestJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(PlainRequestJob.Invoker));


		return services;
	}
}
