//HintName: IJ.Example.SendEmailJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


namespace Example;


partial class SendEmailJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.Storage.IJobStorage storage,
		global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.Interfaces.IIdGenerator idGenerator
	) : global::Immediate.Jobs.Shared.JobScheduler<global::Example.SendEmailJob.Payload>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"send-email",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
	{
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker(global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer) : global::Immediate.Jobs.Shared.Interfaces.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{
			if (execution.Record.Context is { } envelope)
			{
				var contextSlices = global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.Read(envelope);

				global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.LogOrphanedSlices(scopedServices, execution.Record, contextSlices.Keys);
			}

			var payload = serializer.Deserialize(execution.Record.Payload, static options => new PayloadJsonContext(options).Payload);

			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(execution)
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Example.SendEmailJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken);
		}

		/// <summary>Generic reified method to support `struct`s with explicitly implemented properties</summary>
		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	internal sealed record JobDefinition : global::Immediate.Jobs.Shared.Internals.JobDefinition;

	internal static SendEmailJob.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) =>
		new()
		{
			Name = "send-email",
			Queue = new global::Immediate.Jobs.Shared.Internals.JobQueueDefinition
			{
				Name = "default",
				Priority = 0,
				Concurrency = 0,
			},
			Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
			JobType = typeof(global::Example.SendEmailJob),
			TimeZone = "UTC",
			MaxAttempts = 5,
			Timeout = global::System.TimeSpan.Parse("00:02:00", global::System.Globalization.CultureInfo.InvariantCulture),
			MaxConcurrency = 0,
			OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
			Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
			BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
		};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::Example.SendEmailJob.Payload))
				return CreateTypeInfo0(options);

			if (type == typeof(global::System.Guid))
				return CreateTypeInfo1(options);

			if (type == typeof(string))
				return CreateTypeInfo2(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Example.SendEmailJob.Payload> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Example.SendEmailJob.Payload>)GetTypeInfo(
				typeof(global::Example.SendEmailJob.Payload)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Example.SendEmailJob.Payload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Example.SendEmailJob.Payload>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::Example.SendEmailJob.Payload((global::System.Guid)args[0], (string)args[1]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "UserId", ParameterType = typeof(global::System.Guid), Position = 0, HasDefaultValue = false, DefaultValue = default(global::System.Guid) },
					new() { Name = "Template", ParameterType = typeof(string), Position = 1, HasDefaultValue = false, DefaultValue = default(string) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Guid>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::Example.SendEmailJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Guid>)options.GetTypeInfo(typeof(global::System.Guid)),
						Getter = static obj => ((global::Example.SendEmailJob.Payload)obj).UserId,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "UserId",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::Example.SendEmailJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
						Getter = static obj => ((global::Example.SendEmailJob.Payload)obj).Template,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Template",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Example.SendEmailJob.Payload>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Guid> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::System.Guid>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GuidConverter);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> CreateTypeInfo2(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<
				global::Immediate.Jobs.Shared.Internals.JobDefinition,
				SendEmailJob.JobDefinition
			>(SendEmailJob.CreateJobDefinition)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<SendEmailJob.Scheduler>(services);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<
				global::Immediate.Jobs.Shared.Interfaces.IJobScheduler<global::Example.SendEmailJob.Payload>,
				SendEmailJob.Scheduler
			>(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<SendEmailJob.Scheduler>)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<SendEmailJob.Invoker>(services);


		return services;
	}
}
