//HintName: IJOB.global..TenantCleanupJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


public partial class TenantCleanupJob
{

		public sealed class Scheduler(
			global::Immediate.Jobs.Shared.IJobStorage storage,
			global::Immediate.Jobs.Shared.IJobSerializer serializer,
			global::System.TimeProvider timeProvider
		) : global::Immediate.Jobs.Shared.JobScheduler<global::Immediate.Jobs.Shared.NoPayload>(
			storage, serializer, timeProvider, "tenant-cleanup", "default", static options => new PayloadJsonContext(options).Payload),
			global::Immediate.Jobs.Shared.IRecurringJobScheduler
		{

			public global::System.Threading.Tasks.ValueTask<string> TriggerNow(global::System.Threading.CancellationToken cancellationToken = default) =>
				Enqueue(default, cancellationToken);

			public global::System.Threading.Tasks.ValueTask AddOrUpdateRecurring(string name, string cron, string timeZone = "UTC", global::System.Threading.CancellationToken cancellationToken = default) =>
				AddOrUpdateRecurringCore(name, cron, timeZone, cancellationToken);

			public global::System.Threading.Tasks.ValueTask RemoveRecurring(string name, global::System.Threading.CancellationToken cancellationToken = default) =>
				Storage.RemoveRecurringAsync(name, cancellationToken);
		}


	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]

		internal sealed class Invoker : global::Immediate.Jobs.Shared.IJobInvoker

	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{


						var payload = new global::Immediate.Jobs.Shared.NoPayload();

			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(
					execution.Record.Id,
					execution.Record.JobName,
					execution.Record.QueueName,
					execution.Record.Attempt,
					execution.Record.CreatedAt,
					execution.Record.DueAt
				)
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::TenantCleanupJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "tenant-cleanup",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::TenantCleanupJob),

		TimeZone = "UTC",
		MaxAttempts = 3,

		MaxConcurrency = 0,
		OverlapPolicy = (global::Immediate.Jobs.Shared.OverlapPolicy)0,
		Backoff = (global::Immediate.Jobs.Shared.BackoffStrategy)2,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{

						if (type == typeof(global::Immediate.Jobs.Shared.NoPayload)) return CreateTypeInfo0(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.NoPayload> Payload => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.NoPayload>)GetTypeInfo(typeof(global::Immediate.Jobs.Shared.NoPayload))!;



				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.NoPayload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
				{

						var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Immediate.Jobs.Shared.NoPayload>
						{

								ObjectCreator = static () => new global::Immediate.Jobs.Shared.NoPayload(),

							PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
							{

							},
						};
						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Immediate.Jobs.Shared.NoPayload>(options, objectInfo);

					info.OriginatingResolver = this;
					return info;
				}

	}
}
