//HintName: IJ..ContextualJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class ContextualJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.Storage.IJobStorage storage,
		global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.Interfaces.IIdGenerator idGenerator
		, global::CorrelationExtractor contextExtractor0
		, global::UsageContextExtractor contextExtractor1
	) : global::Immediate.Jobs.Shared.JobScheduler<global::ContextualJob.Payload>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"contextual",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
	{
		protected override string? CaptureContext()
		{
			var keys = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);
			var slices = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal);
			if (!keys.Add(contextExtractor0.Key))
				throw new global::Immediate.Jobs.Shared.ImmediateJobException($"Multiple job context extractors use the key '{contextExtractor0.Key}'.");

			var context0 = contextExtractor0.Capture();
			if (context0 is not null)
			{
				global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.AddSlice(
					slices,
					contextExtractor0.Key,
					Serializer.Serialize(context0, static options => new PayloadJsonContext(options).Context0)
				);
			}
			if (!keys.Add(contextExtractor1.Key))
				throw new global::Immediate.Jobs.Shared.ImmediateJobException($"Multiple job context extractors use the key '{contextExtractor1.Key}'.");

			var context1 = contextExtractor1.Capture();
			if (context1 is not null)
			{
				global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.AddSlice(
					slices,
					contextExtractor1.Key,
					Serializer.Serialize(context1, static options => new PayloadJsonContext(options).Context1)
				);
			}
			return global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.Create(slices);
		}

	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker(global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer) : global::Immediate.Jobs.Shared.Interfaces.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{
			if (execution.Record.Context is { } envelope)
			{
				var contextSlices = global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.Read(envelope);

				var contextExtractor0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::CorrelationExtractor>(scopedServices);
				if (contextSlices.Remove(contextExtractor0.Key, out var serializedContext0))
				{
					var context0 = serializer.Deserialize(serializedContext0, static options => new PayloadJsonContext(options).Context0);
					contextExtractor0.Restore(context0);
				}

				var contextExtractor1 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::UsageContextExtractor>(scopedServices);
				if (contextSlices.Remove(contextExtractor1.Key, out var serializedContext1))
				{
					var context1 = serializer.Deserialize(serializedContext1, static options => new PayloadJsonContext(options).Context1);
					contextExtractor1.Restore(context1);
				}

				global::Immediate.Jobs.Shared.Internals.JobContextEnvelope.LogOrphanedSlices(scopedServices, execution.Record, contextSlices.Keys);
			}

			var payload = serializer.Deserialize(execution.Record.Payload, static options => new PayloadJsonContext(options).Payload);

			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(execution)
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ContextualJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		/// <summary>Generic reified method to support `struct`s with explicitly implemented properties</summary>
		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	internal sealed record JobDefinition : global::Immediate.Jobs.Shared.Internals.JobDefinition;

	internal static ContextualJob.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) =>
		new()
    	{
    		Name = "contextual",
			Queue = new global::Immediate.Jobs.Shared.Internals.JobQueueDefinition
    		{
    			Name = "default",
    			Priority = 0,
    			Concurrency = 0,
    		},
    		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
    		JobType = typeof(global::ContextualJob),
    		TimeZone = "UTC",
    		MaxAttempts = 3,
    		MaxConcurrency = 0,
    		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
    		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
    		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
    	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::ContextualJob.Payload))
				return CreateTypeInfo0(options);

			if (type == typeof(string))
				return CreateTypeInfo1(options);

			if (type == typeof(global::CorrelationContext))
				return CreateTypeInfo2(options);

			if (type == typeof(global::UsageContext))
				return CreateTypeInfo3(options);

			if (type == typeof(global::System.Guid))
				return CreateTypeInfo4(options);

			if (type == typeof(global::Region))
				return CreateTypeInfo5(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::ContextualJob.Payload> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::ContextualJob.Payload>)GetTypeInfo(
				typeof(global::ContextualJob.Payload)
			)!;

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CorrelationContext> Context0 =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CorrelationContext>)GetTypeInfo(
				typeof(global::CorrelationContext)
			)!;

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::UsageContext> Context1 =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::UsageContext>)GetTypeInfo(
				typeof(global::UsageContext)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::ContextualJob.Payload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::ContextualJob.Payload>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::ContextualJob.Payload((string)args[0]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "Message", ParameterType = typeof(string), Position = 0, HasDefaultValue = false, DefaultValue = default(string) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::ContextualJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
						Getter = static obj => ((global::ContextualJob.Payload)obj).Message,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Message",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::ContextualJob.Payload>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CorrelationContext> CreateTypeInfo2(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::CorrelationContext>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::CorrelationContext((string)args[0]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "value", ParameterType = typeof(string), Position = 0, HasDefaultValue = false, DefaultValue = default(string) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CorrelationContext),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
						Getter = static obj => ((global::CorrelationContext)obj).Value,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Value",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::CorrelationContext>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::UsageContext> CreateTypeInfo3(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::UsageContext>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::UsageContext((global::System.Guid)args[0], (global::Region)args[1]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "UserId", ParameterType = typeof(global::System.Guid), Position = 0, HasDefaultValue = false, DefaultValue = default(global::System.Guid) },
					new() { Name = "Region", ParameterType = typeof(global::Region), Position = 1, HasDefaultValue = false, DefaultValue = default(global::Region) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Guid>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::UsageContext),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Guid>)options.GetTypeInfo(typeof(global::System.Guid)),
						Getter = static obj => ((global::UsageContext)obj).UserId,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "UserId",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Region>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::UsageContext),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Region>)options.GetTypeInfo(typeof(global::Region)),
						Getter = static obj => ((global::UsageContext)obj).Region,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Region",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::UsageContext>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Guid> CreateTypeInfo4(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::System.Guid>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GuidConverter);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Region> CreateTypeInfo5(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Region>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GetEnumConverter<global::Region>(options));
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<
				global::Immediate.Jobs.Shared.Internals.JobDefinition,
				ContextualJob.JobDefinition
			>(ContextualJob.CreateJobDefinition)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<ContextualJob.Scheduler>(services);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<
				global::Immediate.Jobs.Shared.Interfaces.IJobScheduler<global::ContextualJob.Payload>,
				ContextualJob.Scheduler
			>(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<ContextualJob.Scheduler>)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<ContextualJob.Invoker>(services);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::CorrelationExtractor>(services);
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::UsageContextExtractor>(services);

		return services;
	}
}
