//HintName: IJOB.global..CleanupSessionsJob.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

public partial class CleanupSessionsJob
{
	public interface IScheduler : global::Immediate.Jobs.IRecurringJobScheduler;

	public sealed class Scheduler(
		global::Immediate.Jobs.IJobStorage storage,
		global::Immediate.Jobs.IJobSerializer serializer,
		global::System.TimeProvider timeProvider
	) : global::Immediate.Jobs.JobScheduler<global::Immediate.Jobs.NoPayload>(
		storage, serializer, timeProvider, "cleanup-sessions", "default", static options => new PayloadJsonContext(options).Payload), IScheduler
	{
		public global::System.Threading.Tasks.ValueTask<global::System.Guid> TriggerNow(global::System.Threading.CancellationToken cancellationToken = default) =>
			Enqueue(default, cancellationToken);

		public global::System.Threading.Tasks.ValueTask AddOrUpdateRecurring(string name, string cron, string timeZone = "UTC", global::System.Threading.CancellationToken cancellationToken = default) =>
			AddOrUpdateRecurringCore(name, cron, timeZone, cancellationToken);

		public global::System.Threading.Tasks.ValueTask RemoveRecurring(string name, global::System.Threading.CancellationToken cancellationToken = default) =>
			Storage.RemoveRecurringAsync(name, cancellationToken);
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker : global::Immediate.Jobs.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.JobExecution execution)
		{
			var payload = default(global::Immediate.Jobs.NoPayload);
			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::CleanupSessionsJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "cleanup-sessions",
		Queue = new global::Immediate.Jobs.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::CleanupSessionsJob),
		Cron = "0 */5 * * * *",
		TimeZone = "UTC",
		MaxAttempts = 3,
		MaxConcurrency = 0,
		OverlapPolicy = (global::Immediate.Jobs.OverlapPolicy)0,
		Backoff = (global::Immediate.Jobs.BackoffStrategy)2,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::Immediate.Jobs.NoPayload)) return CreateTypeInfo0(options);
			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.NoPayload> Payload => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.NoPayload>)GetTypeInfo(typeof(global::Immediate.Jobs.NoPayload))!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.NoPayload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Immediate.Jobs.NoPayload>
			{
				ObjectCreator = static () => new global::Immediate.Jobs.NoPayload(),
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Immediate.Jobs.NoPayload>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}
	}
}
