//HintName: IJOB.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Microsoft.Extensions.DependencyInjection;

public static class ImmediateJobsGeneratedServiceCollectionExtensions
{
	public static global::Immediate.Jobs.Shared.ImmediateJobsBuilder AddImmediateJobs(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::System.Action<global::Immediate.Jobs.Shared.ImmediateJobsOptions>? configure = null
	)
	{
		var builder = global::Microsoft.Extensions.DependencyInjection.ImmediateJobsRuntimeServiceCollectionExtensions.AddImmediateJobsCore(services, configure);


				global::ContextualJob.AddHandlers(services);
				global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::ContextualJob.Scheduler));
				global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::ContextualJob.IScheduler), provider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ContextualJob.Scheduler>(provider));
				global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(global::ContextualJob.Invoker));

				global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::CorrelationExtractor));

				global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::UsageContextExtractor));

				services.AddSingleton<global::Immediate.Jobs.Shared.JobDefinition>(provider => global::ContextualJob.CreateJobDefinition(provider));

		return builder;
	}
}
