//HintName: IJ..PlainJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class PlainJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.IJobStorage storage,
		global::Immediate.Jobs.Shared.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.IIdGenerator idGenerator
	) : global::Immediate.Jobs.Shared.JobScheduler<global::Immediate.Jobs.Shared.EmptyJobRequest>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"plain",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
		, global::Immediate.Jobs.Shared.IRecurringJobScheduler
	{
		public new global::Immediate.Jobs.Shared.JobHandle AddToBatch(
			global::Immediate.Jobs.Shared.IJobBatch batch,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::System.TimeSpan? delay = null) =>
			base.AddToBatch(batch, payload, delay);

		public new global::Immediate.Jobs.Shared.JobHandle AddToBatch(
			global::Immediate.Jobs.Shared.IJobBatch batch,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			string? groupId,
			global::System.TimeSpan? delay = null) =>
			base.AddToBatch(batch, payload, groupId, delay);

		public new global::Immediate.Jobs.Shared.JobHandle AddToBatchAt(
			global::Immediate.Jobs.Shared.IJobBatch batch,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::System.DateTimeOffset runAt) =>
			base.AddToBatchAt(batch, payload, runAt);

		public new global::Immediate.Jobs.Shared.JobHandle AddToBatchAt(
			global::Immediate.Jobs.Shared.IJobBatch batch,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::System.DateTimeOffset runAt,
			string? groupId) =>
			base.AddToBatchAt(batch, payload, runAt, groupId);

		public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> ScheduleAfterAsync(
			global::Immediate.Jobs.Shared.JobHandle parent,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::Immediate.Jobs.Shared.ContinuationTrigger on = global::Immediate.Jobs.Shared.ContinuationTrigger.Success,
			global::System.TimeSpan? delay = null,
			global::System.Threading.CancellationToken cancellationToken = default) =>
			base.ScheduleAfterAsync(parent, payload, on, delay, cancellationToken);

		public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> ScheduleAfterAsync(
			global::System.ReadOnlySpan<global::Immediate.Jobs.Shared.JobHandle> parents,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::Immediate.Jobs.Shared.ContinuationTrigger on = global::Immediate.Jobs.Shared.ContinuationTrigger.Success,
			global::System.TimeSpan? delay = null,
			global::System.Threading.CancellationToken cancellationToken = default) =>
			base.ScheduleAfterAsync(parents, payload, on, delay, cancellationToken);

		public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> ScheduleAfterAsync(
			global::Immediate.Jobs.Shared.BatchHandle parent,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::Immediate.Jobs.Shared.ContinuationTrigger on = global::Immediate.Jobs.Shared.ContinuationTrigger.Success,
			global::System.TimeSpan? delay = null,
			global::System.Threading.CancellationToken cancellationToken = default) =>
			base.ScheduleAfterAsync(parent, payload, on, delay, cancellationToken);

		public new global::Immediate.Jobs.Shared.JobHandle ScheduleAfter(
			global::Immediate.Jobs.Shared.JobDetails current,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::Immediate.Jobs.Shared.ContinuationOptions options = global::Immediate.Jobs.Shared.ContinuationOptions.BeforeContinuations) =>
			base.ScheduleAfter(current, payload, options);

		public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> AddToBatchAsync(
			global::Immediate.Jobs.Shared.JobDetails current,
			global::Immediate.Jobs.Shared.EmptyJobRequest payload,
			global::Immediate.Jobs.Shared.ContinuationOptions options = global::Immediate.Jobs.Shared.ContinuationOptions.BeforeContinuations,
			global::System.Threading.CancellationToken cancellationToken = default) =>
			base.AddToBatchAsync(current, payload, options, cancellationToken);

		public global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> TriggerNowAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
			EnqueueAsync(default, cancellationToken);

		public global::System.Threading.Tasks.ValueTask AddOrUpdateRecurringAsync(string name, string cron, string timeZone = "UTC", global::System.Threading.CancellationToken cancellationToken = default) =>
			AddOrUpdateRecurringCoreAsync(name, cron, timeZone, cancellationToken);

		public global::System.Threading.Tasks.ValueTask RemoveRecurringAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) =>
			RemoveRecurringCoreAsync(name, cancellationToken);
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker : global::Immediate.Jobs.Shared.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{

			var payload = new global::Immediate.Jobs.Shared.EmptyJobRequest();

			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(
					execution.Record.Id,
					execution.Record.JobName,
					execution.Record.QueueName,
					execution.Record.Attempt,
					execution.Record.CreatedAt,
					execution.Record.DueAt,
					execution.Record.BatchId
				) { Buffer = execution.Buffer }
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::PlainJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "plain",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::PlainJob),
		TimeZone = "UTC",
		MaxAttempts = 3,
		MaxConcurrency = 0,
		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::Immediate.Jobs.Shared.EmptyJobRequest))
				return CreateTypeInfo0(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest>)GetTypeInfo(
				typeof(global::Immediate.Jobs.Shared.EmptyJobRequest)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Immediate.Jobs.Shared.EmptyJobRequest>
			{
				ObjectCreator = static () => new global::Immediate.Jobs.Shared.EmptyJobRequest(),
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Immediate.Jobs.Shared.EmptyJobRequest>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}
	}


	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		services.Add(
			new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
				typeof(global::Immediate.Jobs.Shared.JobDefinition),
				PlainJob.CreateJobDefinition,
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(PlainJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(PlainJob.Invoker));


		return services;
	}
}
