//HintName: IH.Example.SendEmailJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Example;

partial class SendEmailJob
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::Example.SendEmailJob.Payload, global::System.ValueTuple>
	{
		private readonly global::Example.SendEmailJob.HandleBehavior _handleBehavior;

		public Handler(
			global::Example.SendEmailJob.HandleBehavior handleBehavior
		)
		{
			var handlerType = typeof(SendEmailJob);

			_handleBehavior = handleBehavior;

		}

		public async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::Example.SendEmailJob.Payload request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _handleBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::Example.SendEmailJob.Payload, global::System.ValueTuple>
	{
		private readonly global::Example.SendEmailJob _container;

		public HandleBehavior(
			global::Example.SendEmailJob container
		)
		{
			_container = container;
		}

		public override async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::Example.SendEmailJob.Payload request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			await _container
				.HandleAsync(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);

			return default;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		services.Add(new(typeof(global::Example.SendEmailJob.Handler), typeof(global::Example.SendEmailJob.Handler), lifetime));
		services.Add(new(typeof(global::Immediate.Handlers.Shared.IHandler<global::Example.SendEmailJob.Payload, global::System.ValueTuple>), typeof(global::Example.SendEmailJob.Handler), lifetime));
		services.Add(new(typeof(global::Example.SendEmailJob.HandleBehavior), typeof(global::Example.SendEmailJob.HandleBehavior), lifetime));
		services.Add(new(typeof(global::Example.SendEmailJob), typeof(global::Example.SendEmailJob), lifetime));
		return services;
	}
}
