//HintName: IJ..CollectionJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class CollectionJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.IJobStorage storage,
		global::Immediate.Jobs.Shared.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.IIdGenerator idGenerator
	) : global::Immediate.Jobs.Shared.JobScheduler<global::CollectionJob.Payload>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"collection",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
	{
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker(global::Immediate.Jobs.Shared.IJobSerializer serializer) : global::Immediate.Jobs.Shared.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{

			var payload = serializer.Deserialize(execution.Record.Payload, static options => new PayloadJsonContext(options).Payload);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::CollectionJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "collection",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::CollectionJob),
		TimeZone = "UTC",
		MaxAttempts = 3,
		MaxConcurrency = 0,
		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::CollectionJob.Payload))
				return CreateTypeInfo0(options);

			if (type == typeof(global::Item[]))
				return CreateTypeInfo1(options);

			if (type == typeof(global::Item))
				return CreateTypeInfo2(options);

			if (type == typeof(int))
				return CreateTypeInfo3(options);

			if (type == typeof(global::System.Collections.Generic.List<global::Item>))
				return CreateTypeInfo4(options);

			if (type == typeof(global::System.Collections.Generic.IList<global::Item>))
				return CreateTypeInfo5(options);

			if (type == typeof(global::System.Collections.Generic.IReadOnlyList<global::Item>))
				return CreateTypeInfo6(options);

			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::Item>))
				return CreateTypeInfo7(options);

			if (type == typeof(global::System.Collections.Generic.Dictionary<string, global::Item>))
				return CreateTypeInfo8(options);

			if (type == typeof(string))
				return CreateTypeInfo9(options);

			if (type == typeof(global::System.Collections.Generic.IDictionary<string, global::Item>))
				return CreateTypeInfo10(options);

			if (type == typeof(global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>))
				return CreateTypeInfo11(options);

			if (type == typeof(global::PrivateConstructorValue))
				return CreateTypeInfo12(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CollectionJob.Payload> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CollectionJob.Payload>)GetTypeInfo(
				typeof(global::CollectionJob.Payload)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CollectionJob.Payload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::CollectionJob.Payload>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::CollectionJob.Payload((global::Item[])args[0], (global::System.Collections.Generic.List<global::Item>)args[1], (global::System.Collections.Generic.IList<global::Item>)args[2], (global::System.Collections.Generic.IReadOnlyList<global::Item>)args[3], (global::System.Collections.Generic.IEnumerable<global::Item>)args[4], (global::System.Collections.Generic.Dictionary<string, global::Item>)args[5], (global::System.Collections.Generic.IDictionary<string, global::Item>)args[6], (global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>)args[7], (global::PrivateConstructorValue)args[8]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "Array", ParameterType = typeof(global::Item[]), Position = 0, HasDefaultValue = false, DefaultValue = default(global::Item[]) },
					new() { Name = "List", ParameterType = typeof(global::System.Collections.Generic.List<global::Item>), Position = 1, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.List<global::Item>) },
					new() { Name = "IList", ParameterType = typeof(global::System.Collections.Generic.IList<global::Item>), Position = 2, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.IList<global::Item>) },
					new() { Name = "IReadOnlyList", ParameterType = typeof(global::System.Collections.Generic.IReadOnlyList<global::Item>), Position = 3, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.IReadOnlyList<global::Item>) },
					new() { Name = "IEnumerable", ParameterType = typeof(global::System.Collections.Generic.IEnumerable<global::Item>), Position = 4, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.IEnumerable<global::Item>) },
					new() { Name = "Dictionary", ParameterType = typeof(global::System.Collections.Generic.Dictionary<string, global::Item>), Position = 5, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.Dictionary<string, global::Item>) },
					new() { Name = "IDictionary", ParameterType = typeof(global::System.Collections.Generic.IDictionary<string, global::Item>), Position = 6, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.IDictionary<string, global::Item>) },
					new() { Name = "IReadOnlyDictionary", ParameterType = typeof(global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>), Position = 7, HasDefaultValue = false, DefaultValue = default(global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>) },
					new() { Name = "PrivateConstructor", ParameterType = typeof(global::PrivateConstructorValue), Position = 8, HasDefaultValue = false, DefaultValue = default(global::PrivateConstructorValue) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Item[]>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item[]>)options.GetTypeInfo(typeof(global::Item[])),
						Getter = static obj => ((global::CollectionJob.Payload)obj).Array,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Array",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.List<global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.List<global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).List,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "List",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.IList<global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IList<global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.IList<global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).IList,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "IList",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.IReadOnlyList<global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.IReadOnlyList<global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).IReadOnlyList,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "IReadOnlyList",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.IEnumerable<global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IEnumerable<global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.IEnumerable<global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).IEnumerable,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "IEnumerable",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.Dictionary<string, global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.Dictionary<string, global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).Dictionary,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Dictionary",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.IDictionary<string, global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IDictionary<string, global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.IDictionary<string, global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).IDictionary,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "IDictionary",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>>)options.GetTypeInfo(typeof(global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).IReadOnlyDictionary,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "IReadOnlyDictionary",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::PrivateConstructorValue>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::CollectionJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::PrivateConstructorValue>)options.GetTypeInfo(typeof(global::PrivateConstructorValue)),
						Getter = static obj => ((global::CollectionJob.Payload)obj).PrivateConstructor,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "PrivateConstructor",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::CollectionJob.Payload>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item[]> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateArrayInfo<global::Item>(options, new()
			{
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item> CreateTypeInfo2(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Item>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::Item((int)args[0]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "Value", ParameterType = typeof(int), Position = 0, HasDefaultValue = false, DefaultValue = default(int) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::Item),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int>)options.GetTypeInfo(typeof(int)),
						Getter = static obj => ((global::Item)obj).Value,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Value",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Item>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int> CreateTypeInfo3(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<int>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.Int32Converter);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Item>> CreateTypeInfo4(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateListInfo<global::System.Collections.Generic.List<global::Item>, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.List<global::Item>(),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IList<global::Item>> CreateTypeInfo5(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIListInfo<global::System.Collections.Generic.IList<global::Item>, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.List<global::Item>(),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Item>> CreateTypeInfo6(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIEnumerableInfo<global::System.Collections.Generic.IReadOnlyList<global::Item>, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.List<global::Item>(),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IEnumerable<global::Item>> CreateTypeInfo7(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIEnumerableInfo<global::System.Collections.Generic.IEnumerable<global::Item>, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.List<global::Item>(),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Item>> CreateTypeInfo8(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateDictionaryInfo<global::System.Collections.Generic.Dictionary<string, global::Item>, string, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.Dictionary<string, global::Item>(),
				KeyInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string> CreateTypeInfo9(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<string>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.StringConverter);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IDictionary<string, global::Item>> CreateTypeInfo10(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIDictionaryInfo<global::System.Collections.Generic.IDictionary<string, global::Item>, string, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.Dictionary<string, global::Item>(),
				KeyInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>> CreateTypeInfo11(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIReadOnlyDictionaryInfo<global::System.Collections.Generic.IReadOnlyDictionary<string, global::Item>, string, global::Item>(options, new()
			{
				ObjectCreator = static () => new global::System.Collections.Generic.Dictionary<string, global::Item>(),
				KeyInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
				ElementInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Item>)options.GetTypeInfo(typeof(global::Item)),
			});
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::PrivateConstructorValue> CreateTypeInfo12(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::PrivateConstructorValue>
			{
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::PrivateConstructorValue),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string)),
						Getter = static obj => ((global::PrivateConstructorValue)obj).Value,
						PropertyName = "Value",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::PrivateConstructorValue>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		services.Add(
			new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
				typeof(global::Immediate.Jobs.Shared.JobDefinition),
				CollectionJob.CreateJobDefinition,
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(CollectionJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(CollectionJob.Invoker));


		return services;
	}
}
