//HintName: IH..PlainRequestJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

partial class PlainRequestJob
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::PlainRequestJob.Payload, global::System.ValueTuple>
	{
		private readonly global::PlainRequestJob.HandleBehavior _handleBehavior;

		public Handler(
			global::PlainRequestJob.HandleBehavior handleBehavior
		)
		{
			var handlerType = typeof(PlainRequestJob);

			_handleBehavior = handleBehavior;

		}

		public async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::PlainRequestJob.Payload request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _handleBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::PlainRequestJob.Payload, global::System.ValueTuple>
	{
		private readonly global::PlainRequestJob _container;

		public HandleBehavior(
			global::PlainRequestJob container
		)
		{
			_container = container;
		}

		public override async global::System.Threading.Tasks.ValueTask<global::System.ValueTuple> HandleAsync(
			global::PlainRequestJob.Payload request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			await _container
				.HandleAsync(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);

			return default;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		services.Add(new(typeof(global::PlainRequestJob.Handler), typeof(global::PlainRequestJob.Handler), lifetime));
		services.Add(new(typeof(global::Immediate.Handlers.Shared.IHandler<global::PlainRequestJob.Payload, global::System.ValueTuple>), typeof(global::PlainRequestJob.Handler), lifetime));
		services.Add(new(typeof(global::PlainRequestJob.HandleBehavior), typeof(global::PlainRequestJob.HandleBehavior), lifetime));
		services.Add(new(typeof(global::PlainRequestJob), typeof(global::PlainRequestJob), lifetime));
		return services;
	}
}
