//HintName: IJ..TenantCleanupJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class TenantCleanupJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.Storage.IJobStorage storage,
		global::Immediate.Jobs.Shared.Interfaces.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.Interfaces.IIdGenerator idGenerator
	) : global::Immediate.Jobs.Shared.JobScheduler<global::Immediate.Jobs.Shared.EmptyJobRequest>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"tenant-cleanup",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
		, global::Immediate.Jobs.Shared.Interfaces.IRecurringJobScheduler
	{

		public global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> TriggerNowAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
			EnqueueAsync(default, cancellationToken);

		public global::System.Threading.Tasks.ValueTask AddOrUpdateRecurringAsync(string name, string cron, string timeZone = "UTC", global::System.Threading.CancellationToken cancellationToken = default) =>
			AddOrUpdateRecurringCoreAsync(name, cron, timeZone, cancellationToken);

		public global::System.Threading.Tasks.ValueTask RemoveRecurringAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) =>
			RemoveRecurringCoreAsync(name, cancellationToken);
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker : global::Immediate.Jobs.Shared.Interfaces.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{

			var payload = new global::Immediate.Jobs.Shared.EmptyJobRequest();

			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(execution)
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::TenantCleanupJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		/// <summary>Generic reified method to support `struct`s with explicitly implemented properties</summary>
		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	internal sealed record JobDefinition : global::Immediate.Jobs.Shared.Internals.JobDefinition;

	internal static TenantCleanupJob.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) =>
		new()
    	{
    		Name = "tenant-cleanup",
			Queue = new global::Immediate.Jobs.Shared.Internals.JobQueueDefinition
    		{
    			Name = "default",
    			Priority = 0,
    			Concurrency = 0,
    		},
    		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
    		JobType = typeof(global::TenantCleanupJob),
    		TimeZone = "UTC",
    		MaxAttempts = 3,
    		MaxConcurrency = 0,
    		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
    		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
    		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
    	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::Immediate.Jobs.Shared.EmptyJobRequest))
				return CreateTypeInfo0(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest>)GetTypeInfo(
				typeof(global::Immediate.Jobs.Shared.EmptyJobRequest)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.EmptyJobRequest> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Immediate.Jobs.Shared.EmptyJobRequest>
			{
				ObjectCreator = static () => new global::Immediate.Jobs.Shared.EmptyJobRequest(),
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Immediate.Jobs.Shared.EmptyJobRequest>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<
				global::Immediate.Jobs.Shared.Internals.JobDefinition,
				TenantCleanupJob.JobDefinition
			>(TenantCleanupJob.CreateJobDefinition)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<TenantCleanupJob.Scheduler>(services);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<TenantCleanupJob.Invoker>(services);


		return services;
	}
}
