//HintName: IJ..ClockJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class ClockJob
{
	
		public sealed class Scheduler(
			global::Immediate.Jobs.Shared.IJobStorage storage,
			global::Immediate.Jobs.Shared.IJobSerializer serializer,
			global::System.TimeProvider timeProvider,
			global::Immediate.Jobs.Shared.IIdGenerator idGenerator,
		global::ClockExtractor contextExtractor0
		) : global::Immediate.Jobs.Shared.JobScheduler<global::Immediate.Jobs.Shared.NoPayload>(
			storage, serializer, timeProvider, idGenerator, "clock", "default", static options => new PayloadJsonContext(options).Payload),
			global::Immediate.Jobs.Shared.IRecurringJobScheduler
		{
			
				protected override string? CaptureContext()
				{
					var keys = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);
					var slices = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal);
					
						if (!keys.Add(contextExtractor0.Key))
							throw new global::Immediate.Jobs.Shared.ImmediateJobException($"Multiple job context extractors use the key '{contextExtractor0.Key}'.");
						var context0 = contextExtractor0.Capture();
						if (context0 is not null)
						{
							global::Immediate.Jobs.Shared.JobContextEnvelope.AddSlice(
								slices,
								contextExtractor0.Key,
								Serializer.Serialize(context0, static options => new PayloadJsonContext(options).Context0)
							);
						}
						
					return global::Immediate.Jobs.Shared.JobContextEnvelope.Create(slices);
				}
		
				
			public new global::Immediate.Jobs.Shared.JobHandle AddToBatch(
				global::Immediate.Jobs.Shared.IJobBatch batch,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::System.TimeSpan? delay = null) =>
				base.AddToBatch(batch, payload, delay);
	
			public new global::Immediate.Jobs.Shared.JobHandle AddToBatchAt(
				global::Immediate.Jobs.Shared.IJobBatch batch,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::System.DateTimeOffset runAt) =>
				base.AddToBatchAt(batch, payload, runAt);
	
			public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> ScheduleAfterAsync(
				global::Immediate.Jobs.Shared.JobHandle parent,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::Immediate.Jobs.Shared.ContinuationTrigger on = global::Immediate.Jobs.Shared.ContinuationTrigger.Success,
				global::System.TimeSpan? delay = null,
				global::System.Threading.CancellationToken cancellationToken = default) =>
				base.ScheduleAfterAsync(parent, payload, on, delay, cancellationToken);
	
			public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> ScheduleAfterAsync(
				global::System.ReadOnlySpan<global::Immediate.Jobs.Shared.JobHandle> parents,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::Immediate.Jobs.Shared.ContinuationTrigger on = global::Immediate.Jobs.Shared.ContinuationTrigger.Success,
				global::System.TimeSpan? delay = null,
				global::System.Threading.CancellationToken cancellationToken = default) =>
				base.ScheduleAfterAsync(parents, payload, on, delay, cancellationToken);
	
			public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> ScheduleAfterAsync(
				global::Immediate.Jobs.Shared.BatchHandle parent,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::Immediate.Jobs.Shared.ContinuationTrigger on = global::Immediate.Jobs.Shared.ContinuationTrigger.Success,
				global::System.TimeSpan? delay = null,
				global::System.Threading.CancellationToken cancellationToken = default) =>
				base.ScheduleAfterAsync(parent, payload, on, delay, cancellationToken);
	
			public new global::Immediate.Jobs.Shared.JobHandle ScheduleAfter(
				global::Immediate.Jobs.Shared.JobDetails current,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::Immediate.Jobs.Shared.ContinuationOptions options = global::Immediate.Jobs.Shared.ContinuationOptions.BeforeContinuations) =>
				base.ScheduleAfter(current, payload, options);
	
			public new global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> AddToBatchAsync(
				global::Immediate.Jobs.Shared.JobDetails current,
				global::Immediate.Jobs.Shared.NoPayload payload,
				global::Immediate.Jobs.Shared.ContinuationOptions options = global::Immediate.Jobs.Shared.ContinuationOptions.BeforeContinuations,
				global::System.Threading.CancellationToken cancellationToken = default) =>
				base.AddToBatchAsync(current, payload, options, cancellationToken);
	
			public global::System.Threading.Tasks.ValueTask<global::Immediate.Jobs.Shared.JobHandle> TriggerNowAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
				EnqueueAsync(default, cancellationToken);
		
			public global::System.Threading.Tasks.ValueTask AddOrUpdateRecurringAsync(string name, string cron, string timeZone = "UTC", global::System.Threading.CancellationToken cancellationToken = default) =>
				AddOrUpdateRecurringCoreAsync(name, cron, timeZone, cancellationToken);
	
			public global::System.Threading.Tasks.ValueTask RemoveRecurringAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) =>
				RemoveRecurringCoreAsync(name, cancellationToken);
		}
		

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	
		internal sealed class Invoker(global::Immediate.Jobs.Shared.IJobSerializer serializer) : global::Immediate.Jobs.Shared.IJobInvoker, global::Immediate.Jobs.Shared.IJobContextAwareInvoker
		
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{
			
						if (execution.Record.Context is { } envelope)
						{
							var contextSlices = global::Immediate.Jobs.Shared.JobContextEnvelope.Read(envelope);
							
								var contextExtractor0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ClockExtractor>(scopedServices);
								if (contextSlices.Remove(contextExtractor0.Key, out var serializedContext0))
								{
									var context0 = serializer.Deserialize(serializedContext0, static options => new PayloadJsonContext(options).Context0);
									contextExtractor0.Restore(context0);
								}
								
							global::Immediate.Jobs.Shared.JobContextEnvelope.LogOrphanedSlices(scopedServices, execution.Record, contextSlices.Keys);
						}
						
			
						var payload = new global::Immediate.Jobs.Shared.NoPayload();
						
			SetJobDetails(
				ref payload,
				new global::Immediate.Jobs.Shared.JobDetails(
					execution.Record.Id,
					execution.Record.JobName,
					execution.Record.QueueName,
					execution.Record.Attempt,
					execution.Record.CreatedAt,
					execution.Record.DueAt,
					execution.Record.BatchId
				) { Buffer = execution.Buffer }
			);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ClockJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}

		private static void SetJobDetails<TRequest>(
			ref TRequest request,
			global::Immediate.Jobs.Shared.JobDetails details
		)
			where TRequest : global::Immediate.Jobs.Shared.IJobRequest => request.JobDetails = details;
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "clock",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::ClockJob),
		
		TimeZone = "UTC",
		MaxAttempts = 3,
		
		MaxConcurrency = 0,
		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			
						if (type == typeof(global::Immediate.Jobs.Shared.NoPayload)) return CreateTypeInfo0(options);
						
						if (type == typeof(global::ClockContext)) return CreateTypeInfo1(options);
						
						if (type == typeof(global::NodaTime.Instant)) return CreateTypeInfo2(options);
						
			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.NoPayload> Payload => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.NoPayload>)GetTypeInfo(typeof(global::Immediate.Jobs.Shared.NoPayload))!;
		
				public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::ClockContext> Context0 => (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::ClockContext>)GetTypeInfo(typeof(global::ClockContext))!;
				
		
		
				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Immediate.Jobs.Shared.NoPayload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
				{
					
						var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Immediate.Jobs.Shared.NoPayload>
						{
							
								ObjectCreator = static () => new global::Immediate.Jobs.Shared.NoPayload(),
								
							PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
							{
								
							},
						};
						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Immediate.Jobs.Shared.NoPayload>(options, objectInfo);
						
					info.OriginatingResolver = this;
					return info;
				}
				
		
				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::ClockContext> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
				{
					
						var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::ClockContext>
						{
							
								ObjectWithParameterizedConstructorCreator = static args => new global::ClockContext((global::NodaTime.Instant)args[0]),
								ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
								{
									
										new() { Name = "Now", ParameterType = typeof(global::NodaTime.Instant), Position = 0, HasDefaultValue = false, DefaultValue = default(global::NodaTime.Instant) },
										
								},
								
							PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
							{
								
										global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::NodaTime.Instant>(options, new()
										{
											IsProperty = true,
											IsPublic = true,
											DeclaringType = typeof(global::ClockContext),
											PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::NodaTime.Instant>)options.GetTypeInfo(typeof(global::NodaTime.Instant)),
											Getter = static obj => ((global::ClockContext)obj).Now,
											
												Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
												
											PropertyName = "Now",
										}),
										
							},
						};
						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::ClockContext>(options, objectInfo);
						
					info.OriginatingResolver = this;
					return info;
				}
				
		
				private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::NodaTime.Instant> CreateTypeInfo2(global::System.Text.Json.JsonSerializerOptions options)
				{
					
						var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::NodaTime.Instant>(options, (global::System.Text.Json.Serialization.JsonConverter<global::NodaTime.Instant>)options.GetConverter(typeof(global::NodaTime.Instant)));
						
					info.OriginatingResolver = this;
					return info;
				}
				
	}


	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		services.Add(
			new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
				typeof(global::Immediate.Jobs.Shared.JobDefinition),
				ClockJob.CreateJobDefinition,
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(ClockJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(ClockJob.Invoker));

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(global::ClockExtractor));

		return services;
	}
}
