//HintName: IJ..NullablePayloadJob.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591


partial class NullablePayloadJob
{
	public sealed class Scheduler(
		global::Immediate.Jobs.Shared.IJobStorage storage,
		global::Immediate.Jobs.Shared.IJobSerializer serializer,
		global::System.TimeProvider timeProvider,
		global::Immediate.Jobs.Shared.IIdGenerator idGenerator
	) : global::Immediate.Jobs.Shared.JobScheduler<global::NullablePayloadJob.Payload>(
		storage,
		serializer,
		timeProvider,
		idGenerator,
		"nullable-payload",
		"default",
		static options => new PayloadJsonContext(options).Payload
	)
	{
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal sealed class Invoker(global::Immediate.Jobs.Shared.IJobSerializer serializer) : global::Immediate.Jobs.Shared.IJobInvoker
	{
		public async global::System.Threading.Tasks.ValueTask InvokeAsync(global::System.IServiceProvider scopedServices, global::Immediate.Jobs.Shared.JobExecution execution)
		{

			var payload = serializer.Deserialize(execution.Record.Payload, static options => new PayloadJsonContext(options).Payload);

			var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::NullablePayloadJob.Handler>(scopedServices);
			_ = await handler.HandleAsync(payload, execution.CancellationToken).ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Immediate.Jobs.Shared.JobDefinition CreateJobDefinition(global::System.IServiceProvider services) => new()
	{
		Name = "nullable-payload",
		Queue = new global::Immediate.Jobs.Shared.JobQueueDefinition
		{
			Name = "default",
			Priority = 0,
			Concurrency = 0,
		},
		Invoker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Invoker>(services),
		JobType = typeof(global::NullablePayloadJob),
		TimeZone = "UTC",
		MaxAttempts = 3,
		MaxConcurrency = 0,
		OverlapPolicy = global::Immediate.Jobs.Shared.OverlapPolicy.Skip,
		Backoff = global::Immediate.Jobs.Shared.BackoffStrategy.ExponentialJitter,
		BackoffBase = global::System.TimeSpan.Parse("00:00:05", global::System.Globalization.CultureInfo.InvariantCulture),
	};

	internal sealed class PayloadJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
	{
		private static readonly global::System.Text.Json.JsonSerializerOptions DefaultOptions = new(global::System.Text.Json.JsonSerializerDefaults.Web);
		public static PayloadJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(DefaultOptions));
		protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => DefaultOptions;
		public PayloadJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }
		public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type) =>
			((global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);

		global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
		{
			if (type == typeof(global::NullablePayloadJob.Payload))
				return CreateTypeInfo0(options);

			if (type == typeof(bool))
				return CreateTypeInfo1(options);

			if (type == typeof(long?))
				return CreateTypeInfo2(options);

			if (type == typeof(long))
				return CreateTypeInfo3(options);

			return null;
		}

		public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::NullablePayloadJob.Payload> Payload =>
			(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::NullablePayloadJob.Payload>)GetTypeInfo(
				typeof(global::NullablePayloadJob.Payload)
			)!;

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::NullablePayloadJob.Payload> CreateTypeInfo0(global::System.Text.Json.JsonSerializerOptions options)
		{
			var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::NullablePayloadJob.Payload>
			{
				ObjectWithParameterizedConstructorCreator = static args => new global::NullablePayloadJob.Payload((bool)args[0], (long?)args[1]),
				ConstructorParameterMetadataInitializer = static () => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
				{
					new() { Name = "Reverse", ParameterType = typeof(bool), Position = 0, HasDefaultValue = true, DefaultValue = default(bool) },
					new() { Name = "MaxNodeOption", ParameterType = typeof(long?), Position = 1, HasDefaultValue = true, DefaultValue = default(long?) },
				},
				PropertyMetadataInitializer = _ => new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]
				{
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::NullablePayloadJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<bool>)options.GetTypeInfo(typeof(bool)),
						Getter = static obj => ((global::NullablePayloadJob.Payload)obj).Reverse,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "Reverse",
					}),
					global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<long?>(options, new()
					{
						IsProperty = true,
						IsPublic = true,
						DeclaringType = typeof(global::NullablePayloadJob.Payload),
						PropertyTypeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<long?>)options.GetTypeInfo(typeof(long?)),
						Getter = static obj => ((global::NullablePayloadJob.Payload)obj).MaxNodeOption,
						Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting constructor-bound properties is not supported."),
						PropertyName = "MaxNodeOption",
					}),
				},
			};
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::NullablePayloadJob.Payload>(options, objectInfo);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<bool> CreateTypeInfo1(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<bool>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.BooleanConverter);
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<long?> CreateTypeInfo2(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<long?>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GetNullableConverter<long>(options));
			info.OriginatingResolver = this;
			return info;
		}

		private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<long> CreateTypeInfo3(global::System.Text.Json.JsonSerializerOptions options)
		{
			var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<long>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.Int64Converter);
			info.OriginatingResolver = this;
			return info;
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddJob(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
	)
	{
		services.Add(
			new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
				typeof(global::Immediate.Jobs.Shared.JobDefinition),
				NullablePayloadJob.CreateJobDefinition,
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped(services, typeof(NullablePayloadJob.Scheduler));
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, typeof(NullablePayloadJob.Invoker));


		return services;
	}
}
