<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Title>Immediate.Jobs</Title>
    <Description>A reflection-free background job scheduler for .NET using source generation.</Description>
    <Authors>Immediate.Jobs Developers</Authors>
    <Copyright>© 2026 Immediate.Jobs Developers</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageTags>background-jobs;scheduler;source-generator;aot</PackageTags>
    <RepositoryUrl>https://github.com/ImmediatePlatform/Immediate.Jobs</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
	<NoWarn>$(NoWarn);CA1716</NoWarn>
	<IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../readme.md" Pack="true" PackagePath="/" />
	<None Include="../Immediate.Jobs.Generators/bin/$(Configuration)/netstandard2.0/Immediate.Jobs.Generators.dll"
	      Pack="true"
	      PackagePath="analyzers/dotnet/cs" />
    <PackageReference Include="Cronos" />
    <PackageReference Include="Immediate.Handlers" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Immediate.Jobs.Generators/Immediate.Jobs.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
