<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsAotCompatible>true</IsAotCompatible>
	<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
	<Features>runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Cronos" />
	<PackageReference Include="Immediate.Handlers" />
	<PackageReference Include="Immediate.Validations" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
	<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Immediate.Jobs.Benchmarks" />
	<InternalsVisibleTo Include="Immediate.Jobs.FunctionalTests" />
	<InternalsVisibleTo Include="Immediate.Jobs.StorageTests" />
  </ItemGroup>

</Project>
