<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
	<NoWarn>$(NoWarn);CS1591;CA1050;CA1822</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
	<PackageReference Include="Immediate.Handlers" />
    <ProjectReference Include="../../src/Immediate.Jobs.Shared/Immediate.Jobs.Shared.csproj" />
	<ProjectReference Include="../../src/Immediate.Jobs.Analyzers/Immediate.Jobs.Analyzers.csproj"
	                  OutputItemType="Analyzer"
	                  ReferenceOutputAssembly="false" />
	<ProjectReference Include="../../src/Immediate.Jobs.Generators/Immediate.Jobs.Generators.csproj"
	                  OutputItemType="Analyzer"
	                  ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
