name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: src/Immediate.Jobs.Dashboard/DashboardClient/package-lock.json
      - run: npm ci
        working-directory: src/Immediate.Jobs.Dashboard/DashboardClient
      - run: npm run build
        working-directory: src/Immediate.Jobs.Dashboard/DashboardClient
      - run: dotnet restore Immediate.Jobs.slnx
      - run: dotnet build Immediate.Jobs.slnx -c Release --no-restore
      - run: tests/Immediate.Jobs.Tests/bin/Release/net8.0/Immediate.Jobs.Tests -noColor -noLogo
      - run: tests/Immediate.Jobs.FunctionalTests/bin/Release/net8.0/Immediate.Jobs.FunctionalTests -noColor -noLogo
      - run: dotnet publish samples/NativeAot/NativeAot.csproj -c Release -r linux-x64 --self-contained
      - name: Pack
        run: |
          dotnet pack src/Immediate.Jobs/Immediate.Jobs.csproj -c Release --no-build --no-restore
          dotnet pack src/Immediate.Jobs.Generators/Immediate.Jobs.Generators.csproj -c Release --no-build --no-restore
          dotnet pack src/Immediate.Jobs.EntityFrameworkCore/Immediate.Jobs.EntityFrameworkCore.csproj -c Release --no-build --no-restore
          dotnet pack src/Immediate.Jobs.Dashboard/Immediate.Jobs.Dashboard.csproj -c Release --no-build --no-restore
          dotnet pack src/Immediate.Jobs.NodaTime/Immediate.Jobs.NodaTime.csproj -c Release --no-build --no-restore
          dotnet pack src/Immediate.Jobs.Testing/Immediate.Jobs.Testing.csproj -c Release --no-build --no-restore
      - run: unzip -l src/Immediate.Jobs.Generators/bin/Release/Immediate.Jobs.Generators.1.0.0.nupkg | grep analyzers/dotnet/cs/Immediate.Jobs.Generators.dll
